### ISSUE TITLE
Client class does not accept 'tld' in v1.0.0

### ISSUE THREAD

**Issue by brandoncbryant** [sammchardy/python-binance#803]
**Describe the bug**
The class `Client` does not accept `tld` as an argument after upgrading to v1.0.0. The class `BaseClient`, which `Client` inherits, does accept `tld`, however it has a default value of "com".

**To Reproduce**
```python
from binance.client import Client
client = Client(api_key, api_config, tld='us')
```

**Expected behavior**
Instantiating `Client` would be unchanged from prior version.

**Environment (please complete the following information):**
 - Python version: 3.8
 - Virtual Env: conda
 - OS: Pop!_OS
 - python-binance version: v1.0.0

**Logs or Additional context**
Error output: `TypeError: __init__() got an unexpected keyword argument 'tld'`

**Comment by sammchardy** [comment]
thanks @brandoncbryant have fixed in v1.0.1
